import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import { darkTheme, lightTheme } from "@/utils/theme";
import { ThemeContextProvider } from "@/context/ThemeContext";
import NameContextProvider from "@/context/NameContext";
import Footer from "./components/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kiprono Collins",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}relative bg-[#201d1d] text-white max-w-7xl m-auto`}
      >
        
        <ThemeContextProvider>
          <NameContextProvider>
            <Navbar />
            {children}
            <Footer />
          </NameContextProvider>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
