import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import { darkTheme, lightTheme } from "@/utils/theme";
import { ThemeContextProvider } from "@/context/CounterContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = "dark";

  return (
    <html lang="en">
      <body
        className={`${inter.className} ${
          theme === "dark"
            ? `bg-${darkTheme.bg} text-${darkTheme.text}`
            : `bg-${lightTheme.bg} text-${lightTheme.text} `
        } max-w-7xl m-auto`}
      >
        <Navbar />
        <ThemeContextProvider>{children}</ThemeContextProvider>
      </body>
    </html>
  );
}
